### ISSUE TITLE
Wont work

### ISSUE THREAD

**Issue by ghost** [MinecraftMan1013number2/skGlow#2]
So ive been trying what u said for the other issue and it wont work my skript i put is this
```
            make gui slot 19 with green wool named "Green Glow":
            set {_color} to "green glow" parsed as a glowcolor
            apply {_color} to player

```
dont wanna show the rest of the gui 
but pls help if u can

**Comment by MinecraftMan1013number2** [comment]
Hello! Are there any errors? Does anything happen at all?

**Comment by ghost** [comment]
no errors show up for it but it just dosent do anything

sry for taking a while to respond

wait nvm there is some issues apply {_color} to player says there is no function

**Comment by PELigma** [comment]
sry for taking a while to respond

**Comment by PELigma** [comment]
wait nvm there is some issues apply {_color} to player says there is no function

**Comment by MinecraftMan1013number2** [comment]
Please take a screenshot and send the error here.

**Comment by MinecraftMan1013number2** [comment]
@PELigma any update?

**Comment by ghost** [comment]
sorry for not messaging but you where not the issue. the issue was I didnt know how to use variables but ive learned and it works! Thank you for making this amazing plugin. you are very talented

**Comment by MinecraftMan1013number2** [comment]
No problem! Thank you! If you have any additional suggestions, feel free to let me know!
